[libdefaults]
    default_realm = WSUS.LAB.LOCAL
    dns_lookup_realm = true
    dns_lookup_kdc = true
    rdns = false
    forwardable = true
    udp_preference_limit = 0

[realms]
    WSUS.LAB.LOCAL = {
        kdc = winserver-adcs.wsus.lab.local
        admin_server = winserver-adcs.wsus.lab.local
        default_domain = wsus.lab.local
    }

[domain_realm]
    .wsus.lab.local = WSUS.LAB.LOCAL
    wsus.lab.local = WSUS.LAB.LOCAL
